clear all;

recalculate_simulations = true;   % if recalculate_simulations == false, 
                                   % then separate .mat files are loaded for each activation function 

save_results = true;               % if save_results = true, then separate .mat files are saved for each activation function 

print_title = false;

% subset of inhibition values to be plotted
inhib_subset = 1:4;

addpath('helper_functions');

all_act_fnc = {'knops', 'threshold', 'linear', 'sigmoid', 'relu', 'tanh'};

% Arguments to network functions:
% Simultaneous presentation (we have the max_inhibition_distance_argument):
% Arguments to network functions:
% sequentialPresentation                         true/false
% letNetworkSettleDuringSequentialPresentation   false
% b_arg                                          inhibition value
% useDist                                        false
% snoise_arg                                     sd of noise (0 or .03)
% activation_threshold_arg                       .03
% total_time_steps_arg                           50
% max_inhibition_distance_arg					 Inf
% activation_fnc_arg                             actFncName
% activation_fnc_param_arg                       actFncParam

% Sequential presentation
% sequentialPresentation                         true/false
% letNetworkSettleDuringSequentialPresentation   false
% b_arg                                          inhibition value
% useDist                                        false
% snoise_arg                                     sd of noise (0 or .03)
% activation_threshold_arg                       .03
% total_time_steps_arg                           50
% activation_fnc_arg                             actFncName
% activation_fnc_param_arg                       actFncParam

for act_fnc_ind = 1:length(all_act_fnc)
    
    actFncName = all_act_fnc{act_fnc_ind};
    actFncParam = nan;
    actFncText = get_act_fnc_equation_text(actFncName);
    
    
    if ~recalculate_simulations
        load(['knops_sdt_' actFncName '.mat']);
    end;

    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% %
    % % 1. SIMULTANEOUS PRESENTATION % %
    % %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % 1.1.  Simultaneous Presentation - Noise SD = 0.00 %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    if recalculate_simulations
        [mean_act_sim_n00_b20, faith_sim_n00_b20, inhibition_sim_sum_n00_b20, dprime_sim_n00_b20, bbeta_sim_n00_b20] = ...
            knops_multiple_activation_functions_c(false, false, 0.20, false, .00, .03, 50, Inf, actFncName, actFncParam);
        
        [mean_act_sim_n00_b15, faith_sim_n00_b15, inhibition_sim_sum_n00_b15, dprime_sim_n00_b15, bbeta_sim_n00_b15] = ...
            knops_multiple_activation_functions_c(false, false, 0.15, false, .00, .03, 50, Inf, actFncName, actFncParam);
        
        [mean_act_sim_n00_b10, faith_sim_n00_b10, inhibition_sim_sum_n00_b10, dprime_sim_n00_b10, bbeta_sim_n00_b10] = ...
            knops_multiple_activation_functions_c(false, false, 0.10, false, .00, .03, 50, Inf, actFncName, actFncParam);
        
        [mean_act_sim_n00_b01, faith_sim_n00_b01, inhibition_sim_sum_n00_b01, dprime_sim_n00_b01, bbeta_sim_n00_b01] = ...
            knops_multiple_activation_functions_c(false, false, 0.01, false, .00, .03, 50, Inf, actFncName, actFncParam);        
    
    end; % if recalculate_simulations
    
    make_figure(...
        {mean_act_sim_n00_b01(:,1), ...
        mean_act_sim_n00_b10(:,1), ...
        mean_act_sim_n00_b15(:,1), ...
        mean_act_sim_n00_b20(:,1)}, ...
        'Mean Activation', ...                                % ylab
        'Simultaneous presentation, noise SD = 0', ...        % title
        strcat (repmat ('\beta= ', 4, 1), ...                     % legend
        arrayfun(@(x) num2str(x, '%.2f'), [.01 .1 .15 .2]', ...
        'UniformOutput', false)), ...
        actFncText, ...                                       % annotation
        ['figures_sdt/mean_act_sim_n00_' actFncName '.png'], ...  % file name
        70, ...                                                  % x_max
        print_title, inhib_subset);
    
    make_figure(...
        {1-faith_sim_n00_b01(:,1), ...
        1-faith_sim_n00_b10(:,1), ...
        1-faith_sim_n00_b15(:,1), ...
        1-faith_sim_n00_b20(:,1)}, ...
        'Proportion Correct', ...                                   % ylab
        'Simultaneous presentation, noise SD = 0', ...        % title
        strcat (repmat ('\beta= ', 4, 1), ...                     % legend
        arrayfun(@(x) num2str(x, '%.2f'), [.01 .1 .15 .2]', ...
        'UniformOutput', false)), ...
        actFncText, ...                                       % annotation
        ['figures_sdt/faith_sim_n00_' actFncName '.png'], ...  % file name
        70, ...                                                  % x_max
        print_title, inhib_subset);
        
    make_figure(...
        {dprime_sim_n00_b01(:,1), ...
        dprime_sim_n00_b10(:,1), ...
        dprime_sim_n00_b15(:,1), ...
        dprime_sim_n00_b20(:,1)}, ...
        'd''', ...                                % ylab
        'Simultaneous presentation, noise SD = 0', ...        % title
        strcat (repmat ('\beta= ', 4, 1), ...                     % legend
        arrayfun(@(x) num2str(x, '%.2f'), [.01 .1 .15 .2]', ...
        'UniformOutput', false)), ...
        actFncText, ...                                       % annotation
        ['figures_sdt/dprime_sim_n00_' actFncName '.png'], ...  % file name
        70, ...                                                  % x_max
        print_title, inhib_subset);    
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % 1.2.  Simultaneous Presentation - Noise SD = 0.03 %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    if recalculate_simulations
        [mean_act_sim_n03_b20, faith_sim_n03_b20, inhibition_sim_sum_n03_b20, dprime_sim_n03_b20, bbeta_sim_n03_b20] = ...
            knops_multiple_activation_functions_c(false, false, 0.20, false, .03, .03, 50, Inf, actFncName, actFncParam);
        
        [mean_act_sim_n03_b15, faith_sim_n03_b15, inhibition_sim_sum_n03_b15, dprime_sim_n03_b15, bbeta_sim_n03_b15] = ...
            knops_multiple_activation_functions_c(false, false, 0.15, false, .03, .03, 50, Inf, actFncName, actFncParam);
        
        [mean_act_sim_n03_b10, faith_sim_n03_b10, inhibition_sim_sum_n03_b10, dprime_sim_n03_b10, bbeta_sim_n03_b10] = ...
            knops_multiple_activation_functions_c(false, false, 0.10, false, .03, .03, 50, Inf, actFncName, actFncParam);
        
        [mean_act_sim_n03_b01, faith_sim_n03_b01, inhibition_sim_sum_n03_b01, dprime_sim_n03_b01, bbeta_sim_n03_b01] = ...
            knops_multiple_activation_functions_c(false, false, 0.01, false, .03, .03, 50, Inf, actFncName, actFncParam);
        
    end; % if recalculate_simulations
    
    make_figure(...
        {mean_act_sim_n03_b01(:,1), ...
        mean_act_sim_n03_b10(:,1), ...
        mean_act_sim_n03_b15(:,1), ...
        mean_act_sim_n03_b20(:,1)}, ...
        'Mean Activation', ...                                % ylab
        'Simultaneous presentation, noise SD = 0.03', ...        % title
        strcat (repmat ('\beta= ', 4, 1), ...                     % legend
        arrayfun(@(x) num2str(x, '%.2f'), [.01 .1 .15 .2]', ...
        'UniformOutput', false)), ...
        actFncText, ...                                       % annotation
        ['figures_sdt/mean_act_sim_n03_' actFncName '.png'], ...  % file name
        70, ...                                                  % x_max
        print_title, inhib_subset);
    
    make_figure(...
        {1-faith_sim_n03_b01(:,1), ...
        1-faith_sim_n03_b10(:,1), ...
        1-faith_sim_n03_b15(:,1), ...
        1-faith_sim_n03_b20(:,1)}, ...
        'Proportion Correct', ...                                     % ylab
        'Simultaneous presentation, noise SD = 0.03', ...       % title
        strcat (repmat ('\beta= ', 4, 1), ...                       % legend
        arrayfun(@(x) num2str(x, '%.2f'), [.01 .1 .15 .2]', ...
        'UniformOutput', false)), ...
        actFncText, ...                                         % annotation
        ['figures_sdt/faith_sim_n03_' actFncName '.png'], ...   % file name
        70, ...                                                    % x_max
        print_title, inhib_subset);
     
    make_figure(...
        {dprime_sim_n03_b01(:,1), ...
        dprime_sim_n03_b10(:,1), ...
        dprime_sim_n03_b15(:,1), ...
        dprime_sim_n03_b20(:,1)}, ...
        'd''', ...                                              % ylab
        'Simultaneous presentation, noise SD = 0.03', ...       % title
        strcat (repmat ('\beta= ', 4, 1), ...                       % legend
        arrayfun(@(x) num2str(x, '%.2f'), [.01 .1 .15 .2]', ...
        'UniformOutput', false)), ...
        actFncText, ...                                         % annotation
        ['figures_sdt/dprime_sim_n03_' actFncName '.png'], ...  % file name
        70, ...                                                    % x_max
        print_title, inhib_subset);    
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% %
    % % 2. SEQUENTIAL PRESENTATION - NO CONSOLIDATION % %
    % %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % 2.1. Sequential Presentation - No Consolidation - Noise SD = 0.00 %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    if recalculate_simulations
        %     The code below used knops_maf_track_memory_contents_and_n_activated_units and thus didn't start with set-size 1
        
        % $$$     [mean_act_seq2_n00_b20, faith_seq2_n00_b20, activation_in_early_and_late_targets_seq2_n00_b20, inhibition_seq2_sum_n00_b20, ...
        % $$$         n_active_neurons_seq2_n00_b20, mean_activation_in_active_neurons_seq2_n00_b20, binCounts_seq2_n00_b20, binCounts_by_setSize_seq2_n00_b20, ...
        % $$$         dprime_seq2_n00_b20, bbeta_seq2_n00_b20] = ...
        % $$$         knops_maf_track_memory_contents_and_n_activated_units(true, false, 0.20, false, .00, .03, 50, actFncName, actFncParam);
        % $$$
        % $$$     [mean_act_seq2_n00_b15, faith_seq2_n00_b15, activation_in_early_and_late_targets_seq2_n00_b15, inhibition_seq2_sum_n00_b15, ...
        % $$$         n_active_neurons_seq2_n00_b15, mean_activation_in_active_neurons_seq2_n00_b15, binCounts_seq2_n00_b15, binCounts_by_setSize_seq2_n00_b15, ...
        % $$$         dprime_seq2_n00_b15, bbeta_seq2_n00_b15] = ...
        % $$$         knops_maf_track_memory_contents_and_n_activated_units(true, false, 0.15, false, .00, .03, 50, actFncName, actFncParam);
        % $$$
        % $$$     [mean_act_seq2_n00_b10, faith_seq2_n00_b10, activation_in_early_and_late_targets_seq2_n00_b10, inhibition_seq2_sum_n00_b10, ...
        % $$$         n_active_neurons_seq2_n00_b10, mean_activation_in_active_neurons_seq2_n00_b10, binCounts_seq2_n00_b10, binCounts_by_setSize_seq2_n00_b10, ...
        % $$$         dprime_seq2_n00_b10, bbeta_seq2_n00_b10] = ...
        % $$$         knops_maf_track_memory_contents_and_n_activated_units(true, ...
        % $$$         false, 0.10, false, .00, .03, 50, actFncName, actFncParam);
        % $$$
        % $$$     [mean_act_seq2_n00_b01, faith_seq2_n00_b01, activation_in_early_and_late_targets_seq2_n00_b01, inhibition_seq2_sum_n00_b01, ...
        % $$$         n_active_neurons_seq2_n00_b01, mean_activation_in_active_neurons_seq2_n00_b01, binCounts_seq2_n00_b01, binCounts_by_setSize_seq2_n00_b01, ...
        % $$$         dprime_seq2_n00_b01, bbeta_seq2_n00_b01] = ...
        % $$$         knops_maf_track_memory_contents_and_n_activated_units(true, false, 0.01, false, .00, .03, 50, actFncName, actFncParam);
        
        %     The code below uses knops_multiple_activation_functions
        [mean_act_seq2_n00_b20, faith_seq2_n00_b20, inhibition_seq2_sum_n00_b20, ...
            dprime_seq2_n00_b20, bbeta_seq2_n00_b20] = ...
            knops_multiple_activation_functions_c(true, false, 0.20, false, .00, .03, 50, Inf, actFncName, actFncParam);
        
        [mean_act_seq2_n00_b15, faith_seq2_n00_b15, inhibition_seq2_sum_n00_b15, ...
            dprime_seq2_n00_b15, bbeta_seq2_n00_b15] = ...
            knops_multiple_activation_functions_c(true, false, 0.15, false, .00, .03, 50, Inf, actFncName, actFncParam);
        
        [mean_act_seq2_n00_b10, faith_seq2_n00_b10, inhibition_seq2_sum_n00_b10, ...
            dprime_seq2_n00_b10, bbeta_seq2_n00_b10] = ...
            knops_multiple_activation_functions_c(true, false, 0.10, false, .00, .03, 50, Inf, actFncName, actFncParam);
        
        [mean_act_seq2_n00_b01, faith_seq2_n00_b01, inhibition_seq2_sum_n00_b01, ...
            dprime_seq2_n00_b01, bbeta_seq2_n00_b01] = ...
            knops_multiple_activation_functions_c(true, false, 0.01, false, .00, .03, 50, Inf, actFncName, actFncParam);
        
    end; % if recalculate_simulations
    
    make_figure(...
        {mean_act_seq2_n00_b01(:,1), ...
        mean_act_seq2_n00_b10(:,1), ...
        mean_act_seq2_n00_b15(:,1), ...
        mean_act_seq2_n00_b20(:,1)}, ...
        'Mean Activation', ...                                % ylab
        'Sequential presentation, noise SD = 0', ...        % title
        strcat (repmat ('\beta= ', 4, 1), ...                     % legend
        arrayfun(@(x) num2str(x, '%.2f'), [.01 .1 .15 .2]', ...
        'UniformOutput', false)), ...
        actFncText, ...                                       % annotation
        ['figures_sdt/mean_act_seq2_n00_' actFncName '.png'], ...  % file name
        70, ...                                                  % x_max
        print_title, inhib_subset);
    
    make_figure(...
        {1-faith_seq2_n00_b01(:,1), ...
        1-faith_seq2_n00_b10(:,1), ...
        1-faith_seq2_n00_b15(:,1), ...
        1-faith_seq2_n00_b20(:,1)}, ...
        'Proportion Correct', ...                                   % ylab
        'Sequential presentation, noise SD = 0', ...        % title
        strcat (repmat ('\beta= ', 4, 1), ...                     % legend
        arrayfun(@(x) num2str(x, '%.2f'), [.01 .1 .15 .2]', ...
        'UniformOutput', false)), ...
        actFncText, ...                                       % annotation
        ['figures_sdt/faith_seq2_n00_' actFncName '.png'], ...  % file name
        70, ...                                                  % x_max
        print_title, inhib_subset);
    
    make_figure(...
        {dprime_seq2_n00_b01(:,1), ...
        dprime_seq2_n00_b10(:,1), ...
        dprime_seq2_n00_b15(:,1), ...
        dprime_seq2_n00_b20(:,1)}, ...
        'd''', ...                                % ylab
        'Sequential presentation, noise SD = 0', ...        % title
        strcat (repmat ('\beta= ', 4, 1), ...                     % legend
        arrayfun(@(x) num2str(x, '%.2f'), [.01 .1 .15 .2]', ...
        'UniformOutput', false)), ...
        actFncText, ...                                       % annotation
        ['figures_sdt/dprime_seq2_n00_' actFncName '.png'], ...  % file name
        70, ...                                                  % x_max
        print_title, inhib_subset);    
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % 2.2. Sequential Presentation - No Consolidation - Noise SD = 0.03 %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    if recalculate_simulations
        %     The code below used knops_maf_track_memory_contents_and_n_activated_units and thus didn't start with set-size 1
        
        % $$$     [mean_act_seq2_n03_b20, faith_seq2_n03_b20, activation_in_early_and_late_targets_seq2_n03_b20, inhibition_seq2_sum_n03_b20, ...
        % $$$         n_active_neurons_seq2_n03_b20, mean_activation_in_active_neurons_seq2_n03_b20, binCounts_seq2_n03_b20, binCounts_by_setSize_seq2_n03_b20, ...
        % $$$         dprime_seq2_n03_b20, bbeta_seq2_n03_b20] = ...
        % $$$         knops_maf_track_memory_contents_and_n_activated_units(true, false, 0.20, false, .03, .03, 50, actFncName, actFncParam);
        % $$$
        % $$$     [mean_act_seq2_n03_b15, faith_seq2_n03_b15, activation_in_early_and_late_targets_seq2_n03_b15, inhibition_seq2_sum_n03_b15, ...
        % $$$         n_active_neurons_seq2_n03_b15, mean_activation_in_active_neurons_seq2_n03_b15, binCounts_seq2_n03_b15, binCounts_by_setSize_seq2_n03_b15, ...
        % $$$         dprime_seq2_n03_b15, bbeta_seq2_n03_b15] = ...
        % $$$         knops_maf_track_memory_contents_and_n_activated_units(true, false, 0.15, false, .03, .03, 50, actFncName, actFncParam);
        % $$$
        % $$$     [mean_act_seq2_n03_b10, faith_seq2_n03_b10, activation_in_early_and_late_targets_seq2_n03_b10, inhibition_seq2_sum_n03_b10, ...
        % $$$         n_active_neurons_seq2_n03_b10, mean_activation_in_active_neurons_seq2_n03_b10, binCounts_seq2_n03_b10, binCounts_by_setSize_seq2_n03_b10, ...
        % $$$         dprime_seq2_n03_b10, bbeta_seq2_n03_b10] = ...
        % $$$         knops_maf_track_memory_contents_and_n_activated_units(true, ...
        % $$$         false, 0.10, false, .03, .03, 50, actFncName, actFncParam);
        % $$$
        % $$$     [mean_act_seq2_n03_b01, faith_seq2_n03_b01, activation_in_early_and_late_targets_seq2_n03_b01, inhibition_seq2_sum_n03_b01, ...
        % $$$         n_active_neurons_seq2_n03_b01, mean_activation_in_active_neurons_seq2_n03_b01, binCounts_seq2_n03_b01, binCounts_by_setSize_seq2_n03_b01, ...
        % $$$         dprime_seq2_n03_b01, bbeta_seq2_n03_b01] = ...
        % $$$         knops_maf_track_memory_contents_and_n_activated_units(true, false, 0.01, false, .03, .03, 50, actFncName, actFncParam);
        
        %     The code below uses knops_multiple_activation_functions
        [mean_act_seq2_n03_b20, faith_seq2_n03_b20, inhibition_seq2_sum_n03_b20, ...
            dprime_seq2_n03_b20, bbeta_seq2_n03_b20] = ...
            knops_multiple_activation_functions_c(true, false, 0.20, false, .03, .03, 50, Inf, actFncName, actFncParam);
        
        [mean_act_seq2_n03_b15, faith_seq2_n03_b15, inhibition_seq2_sum_n03_b15, ...
            dprime_seq2_n03_b15, bbeta_seq2_n03_b15] = ...
            knops_multiple_activation_functions_c(true, false, 0.15, false, .03, .03, 50, Inf, actFncName, actFncParam);
        
        [mean_act_seq2_n03_b10, faith_seq2_n03_b10, inhibition_seq2_sum_n03_b10, ...
            dprime_seq2_n03_b10, bbeta_seq2_n03_b10] = ...
            knops_multiple_activation_functions_c(true, false, 0.10, false, .03, .03, 50, Inf, actFncName, actFncParam);
        
        [mean_act_seq2_n03_b01, faith_seq2_n03_b01, inhibition_seq2_sum_n03_b01, ...
            dprime_seq2_n03_b01, bbeta_seq2_n03_b01] = ...
            knops_multiple_activation_functions_c(true, false, 0.01, false, .03, .03, 50, Inf, actFncName, actFncParam);
        
    end; % if recalculate_simulations
    
    make_figure(...
        {mean_act_seq2_n03_b01(:,1), ...
        mean_act_seq2_n03_b10(:,1), ...
        mean_act_seq2_n03_b15(:,1), ...
        mean_act_seq2_n03_b20(:,1)}, ...
        'Mean Activation', ...                                % ylab
        'Sequential presentation, noise SD = 0.03', ...        % title
        strcat (repmat ('\beta= ', 4, 1), ...                     % legend
        arrayfun(@(x) num2str(x, '%.2f'), [.01 .1 .15 .2]', ...
        'UniformOutput', false)), ...
        actFncText, ...                                       % annotation
        ['figures_sdt/mean_act_seq2_n03_' actFncName '.png'], ...  % file name
        70, ...                                                  % x_max
        print_title, inhib_subset);
    
    make_figure(...
        {1-faith_seq2_n03_b01(:,1), ...
        1-faith_seq2_n03_b10(:,1), ...
        1-faith_seq2_n03_b15(:,1), ...
        1-faith_seq2_n03_b20(:,1)}, ...
        'Proportion Correct', ...                                   % ylab
        'Sequential presentation, noise SD = 0.03', ...        % title
        strcat (repmat ('\beta= ', 4, 1), ...                     % legend
        arrayfun(@(x) num2str(x, '%.2f'), [.01 .1 .15 .2]', ...
        'UniformOutput', false)), ...
        actFncText, ...                                       % annotation
        ['figures_sdt/faith_seq2_n03_' actFncName '.png'], ...  % file name
        70, ...                                                  % x_max
        print_title, inhib_subset);
    
    make_figure(...
        {dprime_seq2_n03_b01(:,1), ...
        dprime_seq2_n03_b10(:,1), ...
        dprime_seq2_n03_b15(:,1), ...
        dprime_seq2_n03_b20(:,1)}, ...
        'd''', ...                                % ylab
        'Sequential presentation, noise SD = 0.03', ...        % title
        strcat (repmat ('\beta= ', 4, 1), ...                     % legend
        arrayfun(@(x) num2str(x, '%.2f'), [.01 .1 .15 .2]', ...
        'UniformOutput', false)), ...
        actFncText, ...                                       % annotation
        ['figures_sdt/dprime_seq2_n03_' actFncName '.png'], ...  % file name
        70, ...                                                  % x_max
        print_title, inhib_subset);    
    
    if recalculate_simulations
        if save_results
            savebut(['knops_sdt_' actFncName '.mat'], 'recalculate_simulations',  'save_results', 'print_title', 'inhib_subset');
        end;
    end;

    
end; %act_fnc_ind = 1:length(all_act_fnc)

